name: Check Batch File Safety

on:
  pull_request:
    paths:
      - '**/*.bat'

jobs:
  safety-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Find and analyze batch files
        id: check_files
        run: |
          # Find all .bat files modified in the PR
          batch_files=$(git diff --name-only origin/main | grep '\.bat$')

          if [ -z "$batch_files" ]; then
            echo "No batch files to check."
            exit 0
          fi

          # List of potentially dangerous commands to check
          dangerous_commands="del rd format shutdown"

          # Check each batch file for dangerous commands
          for file in $batch_files; do
            echo "Checking $file for dangerous commands..."
            for cmd in $dangerous_commands; do
              if grep -i -q $cmd "$file"; then
                echo "::error::Dangerous command '$cmd' found in $file"
                echo "unsafe=true" >> $GITHUB_ENV
                exit 1
              fi
            done
          done

          echo "No dangerous commands found in batch files."
          echo "unsafe=false" >> $GITHUB_ENV

      - name: Trigger Close PR Workflow
        if: env.unsafe == 'true'
        run: |
          curl -X POST -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "close_pr", "client_payload": {"pr_number": ${{ github.event.pull_request.number }}}}'
